# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
future: 			 false
markdown: 			 redcarpet
#relative_permalinks: true

# Setup
title:               AB 16' R ile Veri Analizi - Star Group
tagline:             'Akademik Bilişim 2016'
description:         'ABD'de Polis Tarafından Öldürülen İnsanların Analizi'
url:                 http://r338.github.io/ab-2016
baseurl:             '/takim-taslak'
paginate:            5

# About/contact
author:
  name:              'Ümit Işıkdağ, Gözde Yüksel, Ege Savcı'
  url:               http://r338.github.io/takim-taslak
  email:             

# Custom vars
version:             1.0.0
